package gr.alpha.cbs.ml.fuse.referencedata;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-10-13T14:48:12.094+02:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "ReferenceData",
                  wsdlLocation = "/wsdl/ReferenceData.wsdl",
                  targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/")
public class ReferenceData_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fuse.ml.cbs.alpha.gr/ReferenceData/", "ReferenceData");
    public final static QName ReferenceDataSOAP = new QName("http://fuse.ml.cbs.alpha.gr/ReferenceData/", "ReferenceDataSOAP");
    static {
        URL url = ReferenceData_Service.class.getResource("/wsdl/ReferenceData.wsdl");
        if (url == null) {
            url = ReferenceData_Service.class.getClassLoader().getResource("/wsdl/ReferenceData.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(ReferenceData_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "/wsdl/ReferenceData.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReferenceData_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReferenceData_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReferenceData_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReferenceData_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReferenceData_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReferenceData_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReferenceData
     */
    @WebEndpoint(name = "ReferenceDataSOAP")
    public ReferenceData getReferenceDataSOAP() {
        return super.getPort(ReferenceDataSOAP, ReferenceData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReferenceData
     */
    @WebEndpoint(name = "ReferenceDataSOAP")
    public ReferenceData getReferenceDataSOAP(WebServiceFeature... features) {
        return super.getPort(ReferenceDataSOAP, ReferenceData.class, features);
    }

}
