package gr.alpha.cbs.ml.fuse.referencedata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-10-13T14:48:12.057+02:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/", name = "ReferenceData")
@XmlSeeAlso({ObjectFactory.class})
public interface ReferenceData {

    @WebMethod(operationName = "TranslateData", action = "http://fuse.ml.cbs.alpha.gr/ReferenceData/TranslateData")
    @RequestWrapper(localName = "TranslateData", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/", className = "gr.alpha.cbs.ml.fuse.referencedata.TranslateData")
    @ResponseWrapper(localName = "TranslateDataResponse", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/", className = "gr.alpha.cbs.ml.fuse.referencedata.TranslateDataResponse")
    @WebResult(name = "TranslateDataResponsePayload", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/")
    public gr.alpha.cbs.ml.fuse.referencedata.TranslateDataResponsePayload translateData(

        @WebParam(name = "TranslateDataPayload", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/")
        gr.alpha.cbs.ml.fuse.referencedata.TranslateDataPayload translateDataPayload
    );

    @WebMethod(action = "http://fuse.ml.cbs.alpha.gr/ReferenceData/getListReferenceDataItem")
    @RequestWrapper(localName = "getListReferenceDataItem", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/", className = "gr.alpha.cbs.ml.fuse.referencedata.GetListReferenceDataItem")
    @ResponseWrapper(localName = "getListReferenceDataItemResponse", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/", className = "gr.alpha.cbs.ml.fuse.referencedata.GetListReferenceDataItemResponse")
    @WebResult(name = "getListReferenceDataItemResponsePayload", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/")
    public gr.alpha.cbs.ml.fuse.referencedata.GetListReferenceDataItemResponsePayload getListReferenceDataItem(

        @WebParam(name = "getListReferenceDataItemPayload", targetNamespace = "http://fuse.ml.cbs.alpha.gr/ReferenceData/")
        gr.alpha.cbs.ml.fuse.referencedata.GetListReferenceDataItemPayload getListReferenceDataItemPayload
    );
}
